### ISSUE TITLE
styling the profile card

### ISSUE THREAD

**Issue by isiakaabd** [isiakaabd/zuri-developers#1]
## Profile card

The profile card needs cosmetic change

**Comment by ruxy1212** [comment]
![screencapture-file-C-xampp-htdocs-zuri-zuri-developers-index-html-2022-10-27-11_45_16](https://user-images.githubusercontent.com/85977511/198265332-a9e4d0ae-a925-4f62-a48d-6d4a0acbe200.png)
 Not to cosmetic sir, is it?

**Comment by isiakaabd** [comment]
@ruxy1212  This is awesome, send your PR

**Comment by FrancisEdu1** [comment]
Wow... boss when will I be able to design like this?...👏
