### ISSUE TITLE
Card restyling

### ISSUE THREAD

**Issue by Omojole** [isiakaabd/zuri-developers#58]
I would love to make little amends to the cards by changing the background color and dimension of the profile pictures majorly

**Comment by isiakaabd** [comment]
@Omojole, please go ahead, host your branch and send a preview link

**Comment by Omojole** [comment]
> @Omojole, please go ahead, host your branch and send a preview link

here is the preview link,hosted on github [ here](https://omojole.github.io/zuri-developers/)

**Comment by isiakaabd** [comment]
@CRIMSON-CORP @VectorChi  @Omojole  can you guys collaborate on the previous on the new look??? I created a branch for this

**Comment by VectorChi** [comment]
Hmmm. On it. 
After updating my clone with the commits, how do I update on my local machine?

**Comment by Omojole** [comment]
What are you working on?,did a little redesign of the card.. maybe you could check?

**Comment by VectorChi** [comment]
Yes I have seen it. Looks cool. I want to make tiny optimisations. Like the hard shadow

**Comment by Joker4mas** [comment]
> > @Omojole, please go ahead, host your branch and send a preview link
 
> here is the preview link,hosted on github [ here](https://omojole.github.io/zuri-developers/)

The redesigned card is cool,
