### ISSUE TITLE
Using social media icon instead of text

### ISSUE THREAD

**Issue by Odu-dev** [isiakaabd/zuri-developers#7]
May we use social media icon in the stead of text for the social media links

**Comment by isiakaabd** [comment]
@Odu-dev  its assigned to you now, Lemme know if you would need collaboration

**Comment by Odu-dev** [comment]
It's fine, I will just get it done and change it across other profiles

**Comment by FrancisEdu1** [comment]
This is done already.

**Comment by Odu-dev** [comment]
@FrancisEdu1 Thanks for making it happen

**Comment by FrancisEdu1** [comment]
> @FrancisEdu1 Thanks for making it happen

Thank you sir so much and Learnt one and two from it.
