### ISSUE TITLE
Adding a target=-blank to social media handles

### ISSUE THREAD

**Issue by freedomosato** [isiakaabd/zuri-developers#72]
I feel it's better for the social media handle to open in a blank page than to open in it original page. In this way, many contributor's social handle can viewed at same time.

**Comment by CRIMSON-CORP** [comment]
i think this issue is valid @isiakaabd

**Comment by isiakaabd** [comment]
We can use javascript to add that attributes later

**Comment by CRIMSON-CORP** [comment]
Sure, i will add that to my current development
